unbind r
bind r source-file ~/.tmux.conf

#prefix
set -g prefix C-a

#mouse support
set -g mouse on

#pane splitting
#vertical split
unbind v
bind v split-window -h

#horizontal
unbind h
bind h split-window -v

#kill pane
unbind x
bind-key x kill-pane

#new tab
unbind t
bind t new-window

#indexing from 1
set -g base-index 1

#copy mode
unbind c
bind c copy-mode

#renaming session
unbind q
bind q command-prompt "rename-session '%%'"

#renaming window
unbind w
bind w command-prompt "rename-window '%%'"

set -g history-limit 10000
